name: CMake Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
      
    - name: Configure CMake
      run: cmake CMakeLists.txt
      
    - name: Build project
      run: make -j4
