name: CMake Build with Clang

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang

    - name: Build project
      run: |
        mkdir build
        cd build
        CC=clang CXX=clang++ cmake ../CMakeLists.txt
        make -j4
